### ISSUE TITLE
/channels doesn't return a correct "last" header

### ISSUE THREAD

**Issue by SirNickParks** [mixer/developers#161]
As seen in the image below, the "last" header that is supposed to be returned comes back empty.

I already contacted staff in a support ticket about the issue, was advised that the issue is known internally but should create a ticket anyways.

![Image of Postman](https://i.imgur.com/1CgO8uJ.png)

**Comment by SimonSchick** [comment]
This is intentional for the channel page, I will look into updating the documentation here.

We generally don't encourage iterating over API where possible but if you need to you can simply fetch the next page until you receive an empty result.
