### ISSUE TITLE
REST Documentation fixes

### ISSUE THREAD

**Issue by Skriglitz** [mixer/developers#179]
So going through the rest api page I found several things that could be fixed for the documentation pages outlined below. Some may seem quite obvious but I listed them just for the sake of completion

#### /Announcements

Why is there a endpoint to create global announcements for the public rest API but no endpoints to get them without the constellation?

## Models & Types:

_All these should probably be moved to their own page as they are shared with the constellation and rest api_

#### Achievement

No variable descriptions for anything. Also why do achievments have sparks?

#### AchievementEarning

Yes it is obvious but `Achievment` variable has no description. Also probably should be lowercase to match everything else

#### Announcement

`scope` is described as `Unknown`

#### CPMAnalytic

`channel` is also obvious but missing description

#### Channel

`featureLevel` only says `Featuring level`. What is this? what are the levels?

#### ChannelAdvanced

`user` has no description nor mentions of why the line breaks out `groups`

#### Confetti

Should probably mention for this option that currently this is only for partnered streamers

#### CostreamLayout

`name` needs to also include the other layout names.

#### EmojiRankAnalytic

`channel`, `emoji`, and `time` dont have any descriptions

#### FollowersAnalytic

`time` has no description

#### GameRankAnalytic

`channel` and `time` have no description

#### InteractiveControls

`reportInterval` has no description

#### PartnershipApp

`status` has 3 values listed but no description

#### Recording

`state` has 3 values listed but no description

#### Redeemable

`state` has 3 values listed but no description.
`type` lists `pro` as a value but does not list a value for subscriptions

#### Share

`relid` has a description of just `The`.
`code` only says `Share code` but doesn't give much else about it.

#### SparkSpendingAnalytic

`channel` and `time` do not have a description

#### SparkHostsAnalytic

`channel` and `time` do not have a description

#### SparkSessionsAnalytic

`channel` and `time` do not have a description

#### SubRevenueAnalytic

`channel` does not have a description

#### SubscriptionsAnalytic

`channel` and `time` do not have a description

#### ViewerAnalytic

`channel` and `time` do not have a description

#### ViewerMetricAnalytic

`channel` and `time` do not have a description

**Comment by ProbablePrime** [comment]
Huge 👍 here will take this feedback and get some items sorted.

**Comment by ProbablePrime** [comment]
@Skriglitz We've deployed some raml updates to help out here. P{lease let us know if you have any further issues or comments.

Thank you so much!
