### ISSUE TITLE
broadcastEvent is not in protocol.pdf (but is in protocol.rst)

### ISSUE THREAD

**Issue by owenlshinyshoe** [mixer/developers#230]
The documentation for broadcastEvent is in src/reference/interactive/protocol/protocol.rst, but doesn't seem to be in src/reference/interactive/protocol/protocol.pdf.

Update:  It seems like it's changes 1.4.1 and 1.4.2 that aren't showing up in the pdf. 
```
1.4.2 (2018-02-13)
Added world update and change methods.
1.4.1 (2017-10-20)
Added and documented global throtting.
Added the ability to fire one-off events to clients via ``broadcastEvent``.
```

**Comment by ProbablePrime** [comment]
resolved today
